server:
  port: 8093

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: manager-service
          uri: lb://manager-service
          predicates:
            - Path=/manageStaff/**,/manageRoom/**,/inventory/**

          filters:
            - name: CircuitBreaker
              args:
                name: manager-service
                fallbackuri: forward:/managerFallback


        - id: owner-service
          uri: lb://owner-service
          predicates:
            - Path=/manageDepartment/**
          filters:
            - name: CircuitBreaker
              args:
                name: owner-service
                fallbackuri: forward:/ownerFallback

        - id: receptionist-service
          uri: lb://receptionist-service
          predicates:
            - Path=/manageGuest/**,/reservation/**
          filters:
            - name: CircuitBreaker
              args:
                name: receptionist-service
                fallbackuri: forward:/receptionistFallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream