server:
  port: 8093

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: manager-service
          uri: lb://manager-service
          predicates:
            - Path=/manageStaff/**,/manageRoom/**,/inventory/**
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: order-service
        #                fallbackuri: forward:/orderFallback


        - id: owner-service
          uri: lb://owner-service
          predicates:
            - Path=/manageDepartment/**
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: shopping-service
        #                fallbackuri: forward:/shopFallback
        - id: receptionist-service
          uri: lb://receptionist-service
          predicates:
            - Path=/manageGuest/**,/reservation/**
#
#
#
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream